sudo: required
language: java
jdk: oraclejdk13
      
services:
- xvfb

addons:
  chrome: stable

before_install:
  - sudo apt-get update
  - sudo apt-get install dbus-x11
  - sudo apt-get install -y libappindicator1
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/bin
  
script: 
- mvn clean
- mvn test
