sudo: required
language: java
jdk: oraclejdk11

addons:
  chrome: stable

services:
  - xvfb

before_script:
  - sudo apt-get update
  - sudo apt-get install dbus-x11
  - export DISPLAY=:99.0
  - sudo wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /
  - sudo chmod 777 /chromedriver

  
script: 
  - mvn clean
  - mvn test
